ccflags-y += -Idrivers/media/platform/msm/camera_v2_m
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
