ccflags-y += -Idrivers/media/platform/msm/camera_v2_m
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
