ccflags-y += -Idrivers/media/platform/msm/camera_v2_m
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
