#
# Makefile for the HTC power debug device drivers.
#
ccflags-y := -Iinclude/htc_power_debug

obj-$(CONFIG_HTC_POWER_DEBUG_RAILWAYS)	+= htc_railways.o
obj-$(CONFIG_HTC_POWER_DEBUG_RAILWAYS)	+= htc_railways_dbgfs.o
